---
jira:
  projectKey: "JIRATEST1"
  ignore:
    # See the `build-dependencies` group in the Dependabot's configuration file
    - user: dependabot[bot]
      titlePattern: "Bump.*the build-dependencies group( across \\d+ director(ies|y))?( with \\d+ updates?)?"
licenseAgreement:
  enabled: true
